#! /usr/bin/perl
use strict;
use warnings;

my @tests = (
    { file => "string.c", result => 3 }
);

for my $test (@tests) {
    my $output = `clang -I../include -o test/test test/$test->{file}`;

    if ($output) {
        print "test/$test->{file} failed to compile:", "\n\n";
        print $output, "\n\n";
    }

    my $result = `test/test`;

    if ($? != 0 || $result != $test->{result}) {
        print "test/$test->{file} failed:", "\n";
        print "Expected output: $test->{result}", "\n";
        print "Received output: $result", "\n\n\n";
    }
    else {
        print "test/$test->{file} passed.", "\n";
    }
}
